### ISSUE TITLE
httplib not in Python 3

### ISSUE THREAD

**Issue by tschm** [MOSEK/Mosek.pip#2]
Ulf, 
there is a problem in the line 

import httplib

This won't work for Python 3 (3.4.3) on my machine. I recommend you use

from six.moves import http_client

Many thanks
Thomas

**Comment by ulfworsoe** [comment]
I just noticed the thing same today: httplib has become http.client. I'll hopefully have a fix for it tomorrow.

**Comment by tschm** [comment]
You have two options here. See
http://python3porting.com/stdlib.html
Either the 
try/except construction
or 
going via six.moves...

Great job with this package though. This makes life so much easier and makes the installation of Mosek in virtual environments so much easier.

**Comment by ulfworsoe** [comment]
I have hacked a bit on the installer. I went with the 'try import except solution. There is one compromize, though: The requirement "python>=2.5" has to be removed since the setup (even for Python 3) interpreted it as "python>=2.5 and < 3".
Also: Be aware that fusion is not included for Python 3 in MOSEK 7.1.

Please let me know it still causes problem

**Comment by tschm** [comment]
Did you commit your solution?
thomas

**Comment by ulfworsoe** [comment]
Yes, but apparently not to github. It should be up now. Sorry.
